print("Knock knock.")
input()
print("Who's there?")
input()
print("How do dog catchers get paid?")
print()
print("By the pound!")
print("Knock knock.")
input()
print("Who's there?")
input()
print("What does a panda ghost eat?")
print()
print("A Bam-BOO!")
